server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_crud?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug